### ISSUE TITLE
add to weechat.org

### ISSUE THREAD

**Issue by ghost** [s3rvac/weechat-notify-send#1]
please add the script to https://weechat.org/scripts/ so that weechat can install and update the script natively

**Comment by s3rvac** [comment]
Thank you for the idea. I gave this a lot of thought when I made the plugin, and I decided not to do that. The reason is that according to the [weechat script pages](https://weechat.org/scripts/add/), one should not submit scripts that:
- do exactly the same thing as already existing scripts, or
- have the same name as already existing scripts.

There is [notify_send.pl](https://weechat.org/scripts/source/notify_send.pl.html/), which is pretty similar to my plugin, and also uses the same name. Therefore, I did not even try to submit my plugin, because the page says that such scripts will be rejected.

It is still possible to install the script manually. I hope this is not too inconvenient.

**Comment by TRSx80** [comment]
Coming at this from a different perspective, I found your script by searching for "weechat jabber notify" which led me to your [blog post](https://blog.petrzemek.net/2015/08/08/a-new-notification-plugin-for-weechat/) and ultimately, here.

I saw the script of the same name at Weechat (and inside weechat using `/scripts` command) and thought they were the same. It was only when I was trying to change settings that I noticed the one from Weechat repository is a perl script (`/set plugins.var.perl.notify_send.*`) and yours of course is Python. :)

So another reason to consider renaming would be to avoid confusion. How about:

- `notify-send-2` or
- `notify-send-py`

or something like that?

As far as being "the same" there are quite a number of "notification" scripts there, in fact there is a whole tag category "notify."

OTOH, maybe it's more confusing to people to make such change after all this time. I dunno. I guess it would be easy to leave a redirect and short explanation from this repository to the new one...

At any rate, certainly you are free to decide to do whatever you want. I just thought I would register my $0.02. :smile:

Thank you for work, and most importantly for sharing it under open source license like a civilized person! :smile: 

Cheers!

EDIT: After writing this, I went to uninstall the "other" `notify-send` and realized upon closer look that (at least from within Weechat) it shows up as `.pl` extension. So I don't know if they (Weechat) consider the extension to be "different" enough, or if the whole script name needs to be different (and I didn't spend any time to look up their rules regarding). Anyway... thanks again! :smile:
