### ISSUE TITLE
icon not rendedered

### ISSUE THREAD

**Issue by gour** [s3rvac/weechat-notify-send#30]
Hello,

I'm not getting weechat icon displayed in the notification, although I configured:

```
'icon': (
        '/path/to/Pictures/weechat.png',
        'Path to an icon to be shown in notifications.'
    ),
```

In the beginning I thought it is maybe due to using `*.xpm`, but even after converting to `*.png` it is the same.

Any hint?

**Comment by s3rvac** [comment]
Hi! This option works well on my machine, so we will need to debug the issue on your machine. :slightly_smiling_face: Could you please run the following command from the terminal and let me know if a the icon is properly shown in the notification?
```
notify-send --icon /path/to/Pictures/weechat.png test
```
What I am trying to determine first is if the issue is in the weechat-notify-send script, its configuration, or in the system.

If the command above does not result in a notification with a properly shown icon, could you please try downloading the icon below and running the command with it instead?

Here is the sample icon:
![notification](https://user-images.githubusercontent.com/5675953/133930237-c5a63571-b6bf-41f0-858b-610fa3ba8637.png)

**Comment by gour** [comment]
> Hi! This option works well on my machine, so we will need to debug the issue on your machine. slightly_smiling_face

:wink: 
> Could you please run the following command from the terminal and let me know if a the icon is properly shown in the notification?
> 
> ```
> notify-send --icon /path/to/Pictures/weechat.png test
> ```

It does work!

**Comment by s3rvac** [comment]
OK, great. Now, let's check if you have a proper icon path in the configuration of the notification script: Could you please start WeeChat, run the following command to get the icon path, and check whether it is correct?
```
/set plugins.var.python.notify_send.icon
```
To set a new icon path, run
```
/set plugins.var.python.notify_send.icon /path/to/Pictures/weechat.png
```

**Comment by s3rvac** [comment]
Solved by changing the `plugins.var.python.notify_send.icon` configuration option in WeeChat.
